baseURL = "https://mrsnailo.github.io/website"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "github.com/adityatelange/hugo-PaperMod"




[module]
[[module.import]]
path = "github.com/adityatelange/hugo-PaperMod.git"