[[main]]
name = "Posts"
url = "posts/"
weight = 1

[[main]]
name = "Tags"
url = "tags/"
weight = 2

[[main]]
name= "Categories"
url = "categories/"
weight = 3

[[main]]
name = "Search"
url = "search/"
weight = 4