author = "Shahid Parvez"
defaultTheme = 'light'

ShowShareButtons = true 
ShowReadingTime = true
showToc = true
tocOpen = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = true
images = ['/assets/cover/cover.png']

[label]
text = "‍@shahidparvez"
icon = "/assets/icons/favicon/48x48.png"
iconHeight = 32


[assets]
favicon = "/assets/icons/favicon/48x48.png"

[profileMode]
enabled = true
title = "শাহিদ পারভেজ"
subtitle = "Linux-Lover"
imageUrl = "assets/logo/avatar.png"
imageTitle = "Avatar"
imageWidth = 180
imageHeight = 180

[cover]
image = ['/assets/cover/cover.png']
alt = "Cover"
captions = "Reading Makes You Feel Good"

[[profileMode.buttons]]
name = "About Me"
url = "about/"
# entry 2
[[profileMode.buttons]]
name = 'Posts'
url = 'posts/'



# Social Icon

[[socialIcons]]
name = "Github"
url = "https://github.com/mrsnailo"

[[socialIcons]]
name = "Twitter"
url = "https://twitter.com/mrsnailo"

[[socialIcons]]
name = "Reddit"
url = "https://reddit.com/mrsnailo"

[[socialIcons]]
name = "Instagram"
url = "https://Instagram.com/mrsnailo"

[[socialIcons]]
name = "Telegram"
url = "https://t.me/prismoidparvez"

[[socialIcons]]
name = "Discord"
url = "https://discord.com/users/573172734767661056"


# Suggest Changes
[editPost]
    URL = "https://github.com/mrsnailo/mrsnailo.github.io/tree/master/content/"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link