author = "Shahid Parvez"
defaultTheme = 'light'

ShowShareButtons = true 
ShowReadingTime = true
showToc = true
tocOpen = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = true

[label]
text = "‍@shahidparvez"
icon = "/assets/icon/favicon/32x32.png"
iconHeight = 32

# favicons
[assets]
    favicon = "/assets/icon/favicon/32x32.png"
    favicon16x16 =  "/assets/icon/favicon/32x32.png"


[profileMode]
enabled = true
title = "শাহিদ পারভেজ"
subtitle = "Linux-Lover"
imageUrl = "/assets/logo/avatar.png"
imageTitle = "Avatar"
imageWidth = 180
imageHeight = 180



[[profileMode.buttons]]
name = "About Me"
url = "/about"
# entry 2
[[profileMode.buttons]]
name = 'Posts'
url = '/posts/'



# Social Icon

[[socialIcons]]
name = "Github"
url = "https://github.com/mrsnailo"


# Suggest Changes
[editPost]
    URL = "https://github.com/mrsnailo/mrsnailo.github.io/content"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link