
name: Hugo
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: prepare(hugo)
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest

    - name: prepare(node)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: init-cache(hugo)
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-hugomod-${{ hashFiles('go.sum') }}
        path: /tmp/hugo_cache
        restore-keys: ${{ runner.os }}-hugomod-

    - name: init-cache(node)
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        path: ./node_modules
        restore-keys: ${{ runner.os }}-npm-

    - name: build(site)
      run: ./build.sh
      shell: sh
    
    - name: push(site)
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn
    

  deploy:
    # runs-on: ubuntu-18.04
    # needs: build
    # steps:
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     personal_token: ${{ secrets.HTOKEN }}
    #     external_repository:  mrsnailo/mrsnailo.github.io
    #     publish_dir: ./public
    #     #   keep_files: true for
    #     # uncomment if need backup files
    #     user_name: mrsnailo
    #     user_email: shahidparvez.official@gmail.com
    #     publish_branch: master
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
    - name: deploy(site)
      uses: actions/deploy-pages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 600000
        error_count: 10
        reporting_interval: 1000